# Generated by Django 4.2.8 on 2025-03-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0002_item_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(default=""),
        ),
    ]
